extends SceneTree
## tools/test_editor.gd: headless checks of the editor's core (no window, no pipeline).
##   godot --headless --path tools/pixelforge/forge --script res://tools/test_editor.gd
## Palette lock snapping, fill, wand, undo/redo round trip, clone offset, carry by frame index, anchors, the command
## line of the editor screen's exec. Exit code 1 when any check fails.

const Pal := preload("res://scripts/editor/palette.gd")
const Px := preload("res://scripts/editor/pixels.gd")
const Doc := preload("res://scripts/editor/document.gd")
const Hist := preload("res://scripts/editor/history.gd")
const Carry := preload("res://scripts/editor/carry.gd")
const Anchors := preload("res://scripts/editor/anchors.gd")

var fails := 0
var checks := 0
var tmp := ""

func ok(cond: bool, what: String) -> void:
	checks += 1
	if not cond:
		fails += 1
		print("FAIL ", what)

func _init() -> void:
	tmp = OS.get_user_data_dir().path_join("editor_test")
	_rm(tmp)
	DirAccess.make_dir_recursive_absolute(tmp)
	test_oklab()
	test_palette_lock()
	test_points()
	test_fill_and_wand()
	test_masks()
	test_history_round_trip()
	test_clone_offset()
	test_carry_by_index()
	test_anchors()
	test_exec()
	print("editor checks: %d run, %d failed" % [checks, fails])
	quit(1 if fails > 0 else 0)

static func _rm(path: String) -> void:
	var d := DirAccess.open(path)
	if d == null:
		return
	d.include_hidden = true
	for f in d.get_files():
		DirAccess.remove_absolute(path.path_join(f))
	for sub in d.get_directories():
		_rm(path.path_join(sub))
	DirAccess.remove_absolute(path)

func test_oklab() -> void:
	var w := Pal.to_oklab(Color.WHITE)
	ok(absf(w.x - 1.0) < 0.01 and absf(w.y) < 0.01 and absf(w.z) < 0.01, "white is L=1 in OKLab: %s" % w)
	var k := Pal.to_oklab(Color.BLACK)
	ok(absf(k.x) < 0.01, "black is L=0")
	var c := Color("#d9b05c")
	var back := Pal.from_oklab(Pal.to_oklab(c))
	ok(Pal.same_rgb(c, back), "OKLab round trip keeps the ember gold: %s -> %s" % [c.to_html(false), back.to_html(false)])
	ok(Pal.distance(Color.RED, Color("#ff0101")) < Pal.distance(Color.RED, Color.BLUE), "near colours are near")

func test_palette_lock() -> void:
	var p := Pal.new()
	var img := Px.blank(4, 1)
	img.set_pixel(0, 0, Color("#102030"))
	img.set_pixel(1, 0, Color("#d9b05c"))
	img.set_pixel(2, 0, Color("#ffffff"))
	p.add_image(img)
	ok(p.size() == 3, "three colours found (%d)" % p.size())
	var r := p.resolve(Color("#d8b15d"))
	ok(r["snapped"] and r["slot"] == 1 and Pal.same_rgb(r["colour"], Color("#d9b05c")), "locked snaps a near gold to slot 1: %s" % r)
	ok(p.size() == 3 and p.added == 0, "locked adds nothing")
	var exact := p.resolve(Color("#102030"))
	ok(not exact["snapped"] and exact["slot"] == 0, "an exact colour is its own slot")
	p.mode = Pal.OPEN
	var o := p.resolve(Color("#00ff00"))
	ok(o["added"] and p.size() == 4 and p.added == 1 and o["slot"] == 3, "open lets a colour in and counts it: %s" % o)
	var again := p.resolve(Color("#00ff00"))
	ok(not again["added"] and p.added == 1, "the same colour again is not counted twice")
	ok(p.resolve(Color(0, 0, 0, 0))["slot"] == -1, "see-through resolves to no slot")

func test_points() -> void:
	ok(Px.line_points(Vector2i(0, 0), Vector2i(3, 0)).size() == 4, "a line of four")
	ok(Px.line_points(Vector2i(0, 0), Vector2i(2, 2)).size() == 3, "a diagonal has no gaps and no doubles")
	ok(Px.brush_points(Vector2i(5, 5), 1).size() == 1 and Px.brush_points(Vector2i(5, 5), 2).size() == 4 and Px.brush_points(Vector2i(5, 5), 3).size() == 5, "brush tips 1, 2, 3")
	var b5 := Px.brush_points(Vector2i(5, 5), 5)
	ok(b5.size() >= 13 and b5.size() <= 21, "a 5 brush is a round dot (%d)" % b5.size())
	ok(Px.rect_points(Vector2i(0, 0), Vector2i(3, 2), false).size() == 10 and Px.rect_points(Vector2i(0, 0), Vector2i(3, 2), true).size() == 12, "rectangle outline and filled")
	var e := Px.ellipse_points(Vector2i(0, 0), Vector2i(8, 4), true)
	ok(e.size() > 20 and e.size() < 45, "an ellipse fills about pi/4 of its box (%d)" % e.size())
	var eo := Px.ellipse_points(Vector2i(0, 0), Vector2i(8, 4), false)
	ok(eo.size() < e.size() and eo.size() > 10, "its outline is thinner (%d)" % eo.size())

func _two_tone() -> Image:
	var img := Px.blank(8, 8)
	for y in 8:
		for x in 8:
			img.set_pixel(x, y, Color("#303030") if x < 4 else Color("#c0c0c0"))
	img.set_pixel(0, 0, Color(0, 0, 0, 0))
	return img

func test_fill_and_wand() -> void:
	var img := _two_tone()
	var n := Px.fill(img, Vector2i(1, 1), Color("#ff0000"), true, 0.0, PackedByteArray())
	ok(n == 31, "contiguous fill paints the dark half but not the clear corner (%d)" % n)
	ok(img.get_pixel(0, 0).a == 0.0 and Pal.same_rgb(img.get_pixel(5, 5), Color("#c0c0c0")), "the fill stayed in its region")
	var img2 := _two_tone()
	img2.set_pixel(6, 6, Color("#303030"))   # an island of the dark tone in the light half
	var g := Px.fill(img2, Vector2i(1, 1), Color("#00ff00"), false, 0.0, PackedByteArray())
	ok(g == 32, "global fill reaches the island too (%d)" % g)
	var m := Px.flood_mask(_two_tone(), Vector2i(6, 1), 0.0, true)
	ok(Px.mask_count(m) == 32, "the wand on the light half takes 32 (%d)" % Px.mask_count(m))
	var tol := Px.flood_mask(_two_tone(), Vector2i(6, 1), 1.0, true)
	ok(Px.mask_count(tol) == 63, "a wide tolerance takes every painted pixel (%d)" % Px.mask_count(tol))
	var clear := Px.flood_mask(_two_tone(), Vector2i(0, 0), 0.0, true)
	ok(Px.mask_count(clear) == 1, "the wand on see-through takes see-through only")
	# a fill inside a selection stays inside it
	var sel := Px.rect_mask(8, 8, Vector2i(0, 0), Vector2i(1, 7))
	var img3 := _two_tone()
	var k := Px.fill(img3, Vector2i(1, 1), Color("#0000ff"), true, 0.0, sel)
	ok(k == 15, "a fill respects the selection (%d)" % k)

func test_masks() -> void:
	var a := Px.rect_mask(8, 8, Vector2i(0, 0), Vector2i(3, 3))
	var b := Px.rect_mask(8, 8, Vector2i(2, 2), Vector2i(5, 5))
	ok(Px.mask_count(Px.mask_combine(a, b, "add")) == 28, "shift adds")
	ok(Px.mask_count(Px.mask_combine(a, b, "subtract")) == 12, "alt subtracts")
	ok(Px.mask_count(Px.mask_combine(a, b, "intersect")) == 4, "intersect")
	ok(Px.mask_bounds(b, 8, 8) == Rect2i(2, 2, 4, 4), "bounds")
	var lasso := Px.polygon_mask(8, 8, [Vector2i(0, 0), Vector2i(8, 0), Vector2i(8, 8), Vector2i(0, 8)])
	ok(Px.mask_count(lasso) == 64, "a lasso round everything takes everything (%d)" % Px.mask_count(lasso))
	var tri := Px.polygon_mask(8, 8, [Vector2i(0, 0), Vector2i(8, 0), Vector2i(0, 8)])
	ok(Px.mask_count(tri) > 24 and Px.mask_count(tri) < 40, "a triangle takes about half (%d)" % Px.mask_count(tri))
	ok(Px.mask_count(Px.mask_invert(a, 8, 8)) == 48, "invert")
	var shifted := Px.mask_shift(a, 8, 8, Vector2i(6, 0))
	ok(Px.mask_count(shifted) == 8, "a shift off the edge drops what left")
	# mirror within the selection only
	var img := Px.blank(8, 1)
	for x in 8:
		img.set_pixel(x, 0, Color8(x * 30, 0, 0))
	Px.flip(img, Px.rect_mask(8, 1, Vector2i(0, 0), Vector2i(3, 0)), true)
	ok(img.get_pixel(0, 0).r8 == 90 and img.get_pixel(3, 0).r8 == 0 and img.get_pixel(7, 0).r8 == 210, "mirror flips the selection and leaves the rest")
	var nud := Px.blank(4, 4)
	nud.set_pixel(0, 0, Color.WHITE)
	var m := Px.nudge(nud, Px.rect_mask(4, 4, Vector2i(0, 0), Vector2i(0, 0)), Vector2i(2, 1), false)
	ok(nud.get_pixel(0, 0).a == 0.0 and nud.get_pixel(2, 1).a == 1.0 and m[1 * 4 + 2] == 1, "nudge moves pixels and the selection")

## a frame set on disk: two clips, three directions, three frames each
func _make_set(dir: String) -> void:
	for k in ["idle_S", "idle_E", "idle_N", "walk_S"]:
		DirAccess.make_dir_recursive_absolute(dir.path_join(k))
		for i in 3:
			var img := Px.blank(16, 16)
			for y in range(4, 12):
				for x in range(4 + i, 12 + i):
					img.set_pixel(x, y, Color("#406080") if k.ends_with("_S") else Color("#804060"))
			img.save_png(dir.path_join(k).path_join("frame_%03d.png" % i))
	var f := FileAccess.open(dir.path_join("animations.json"), FileAccess.WRITE)
	f.store_string(JSON.stringify({"clip_fps": {"idle": 8, "walk": 12}}))

func test_history_round_trip() -> void:
	var dir := tmp.path_join("set_a")
	_make_set(dir)
	var doc := Doc.new()
	ok(doc.open_set(dir, "idle", "S"), "the set opens")
	ok(doc.keys.size() == 4 and doc.count() == 3 and doc.width == 16 and doc.fps == 8.0, "4 folders, 3 frames, 16 px, 8 fps (%s %d %d %s)" % [doc.keys, doc.count(), doc.width, doc.fps])
	ok(doc.palette.size() == 2, "the set's palette has its two colours (%d)" % doc.palette.size())
	var h := Hist.new()
	var L := doc.layer()
	ok(L.name == "paint", "the paint layer is active")
	h.begin("pencil", doc.selection)
	h.touch(doc.current(), doc.active_layer)
	Px.apply(L.image, [Vector2i(5, 5), Vector2i(6, 5)], Color("#406080"), doc.selection)
	var e = h.commit(doc.selection)
	ok(e != null and e.touched == 2 and h.cursor == 1, "one entry of two pixels (%s %s %d)" % [e, e.touched if e else -1, h.cursor])
	h.begin("brush", doc.selection)
	h.touch(doc.current(), doc.active_layer)
	Px.apply(L.image, Px.brush_points(Vector2i(8, 8), 3), Color("#804060"), doc.selection)
	h.commit(doc.selection)
	ok(h.entries.size() == 2, "two entries")
	ok(doc.composite().get_pixel(8, 8).to_html(false) == "804060", "the composite shows the brush")
	h.undo()
	ok(doc.layer().image.get_pixel(8, 8).a == 0.0 and doc.layer().image.get_pixel(5, 5).a == 1.0, "undo takes the brush back, keeps the pencil")
	h.undo()
	ok(doc.layer().image.get_pixel(5, 5).a == 0.0, "undo again clears the pencil")
	ok(not h.can_undo() and h.can_redo(), "at the start; redo available")
	h.redo()
	h.redo()
	ok(doc.layer().image.get_pixel(8, 8).a == 1.0 and doc.layer().image.get_pixel(5, 5).a == 1.0, "redo twice restores both")
	h.goto(1)
	ok(doc.layer().image.get_pixel(8, 8).a == 0.0 and h.cursor == 1, "goto 1 leaves the pencil only")
	h.begin("after", doc.selection)
	h.touch(doc.current(), doc.active_layer)
	Px.apply(doc.layer().image, [Vector2i(1, 1)], Color("#406080"), doc.selection)
	h.commit(doc.selection)
	ok(h.entries.size() == 2 and not h.can_redo(), "a new change after an undo drops the redo branch")
	# an entry that changes nothing is dropped
	h.begin("nothing", doc.selection)
	h.touch(doc.current(), doc.active_layer)
	ok(h.commit(doc.selection) == null and h.entries.size() == 2, "an empty entry is dropped")
	# saving flattens
	ok(doc.save_all() == 1, "one dirty frame saved")
	var back := Image.load_from_file(doc.frame_path("idle_S", 0))
	ok(back.get_pixel(1, 1).to_html(false) == "406080", "the saved frame has the paint flattened in")
	ok(FileAccess.file_exists(dir.path_join(".layers/idle_S/frame_000.paint.png")), "the paint layer is kept beside")
	ok(h.lines().size() == 2 and h.lines()[0].begins_with("1  pencil"), "the history reads as lines: %s" % h.lines())

func test_clone_offset() -> void:
	var src := Px.blank(8, 8)
	src.set_pixel(1, 1, Color("#ff0000"))
	src.set_pixel(2, 1, Color("#00ff00"))
	var dst := Px.blank(8, 8)
	var offset := Vector2i(4, 4)   # dest - source: painting at (5,5) samples (1,1)
	var n := Px.clone(dst, src, [Vector2i(5, 5), Vector2i(6, 5), Vector2i(7, 7)], offset, PackedByteArray(), Callable())
	ok(n == 2, "two pixels cloned, the bare one skipped (%d)" % n)
	ok(dst.get_pixel(5, 5).to_html(false) == "ff0000" and dst.get_pixel(6, 5).to_html(false) == "00ff00", "the offset follows the brush")
	var p := Pal.new()
	var pal_img := Px.blank(1, 1)
	pal_img.set_pixel(0, 0, Color("#800000"))
	p.add_image(pal_img)
	var dst2 := Px.blank(8, 8)
	Px.clone(dst2, src, [Vector2i(5, 5)], offset, PackedByteArray(), p.snap)
	ok(dst2.get_pixel(5, 5).to_html(false) == "800000", "a clone goes through the palette lock")

func test_carry_by_index() -> void:
	var dir := tmp.path_join("set_b")
	_make_set(dir)
	var doc := Doc.new()
	doc.open_set(dir, "idle", "S")
	doc.index = 1
	var h := Hist.new()
	h.begin("pencil", doc.selection)
	h.touch(doc.current(), doc.active_layer)
	# two pixels on the figure (frame 1 is shifted one right: figure spans x 5..12), one off it at (1, 1)
	Px.apply(doc.layer().image, [Vector2i(6, 6), Vector2i(12, 6), Vector2i(1, 1)], Color("#ffffff"), doc.selection)
	h.commit(doc.selection)
	var r := Carry.run(doc, h, Carry.SCOPE_DIRS)
	ok(r["ok"] and r["landed"].size() == 2, "carry to directions lands on idle_E and idle_N (%s)" % str(r.get("landed", []).size()))
	ok(r["by"] == "position", "no part masks: by position")
	for L in r["landed"]:
		ok(L["index"] == 1, "the same frame index")
	var e := doc.frame("idle_E", 1)
	ok(e.layers[1].image.get_pixel(6, 6).a == 1.0 and e.layers[1].image.get_pixel(1, 1).a == 1.0, "a pixel on the figure and one off it land")
	ok(doc.frame("idle_S", 0).layers[1].image.get_pixel(6, 6).a == 0.0, "the clip's other frames were not touched by a directions carry")
	ok(h.entries.size() == 2 and h.last().label == "carry directions", "the carry is one history entry")
	h.undo()
	ok(doc.frame("idle_E", 1).layers[1].image.get_pixel(6, 6).a == 0.0, "undo takes the carry back everywhere")
	h.redo()
	var r2 := Carry.run(doc, h, Carry.SCOPE_CLIP, h.entries[0])
	ok(r2["ok"] and r2["landed"].size() == 2, "carry to the clip lands on the two other frames")
	# position matters: frame 2's figure spans 6..13, so (12,6) lands; frame 0's spans 4..11 so the pixel at 12 is off the figure and skipped (the source had figure there)
	var f0 := doc.frame("idle_S", 0)
	var f2 := doc.frame("idle_S", 2)
	ok(f2.layers[1].image.get_pixel(12, 6).a == 1.0 and f0.layers[1].image.get_pixel(12, 6).a == 0.0, "by position: a figure pixel lands only where the target has the figure")
	var walk := Carry.run(doc, h, Carry.SCOPE_ALL, h.entries[0])
	ok(walk["ok"] and walk.get("landed", []).size() == 4, "carry all: 2 frames + 2 directions, never the walk clip (%d)" % walk.get("landed", []).size())
	var hh := Hist.new()
	ok(not Carry.run(doc, hh, Carry.SCOPE_ALL)["ok"], "nothing to carry says so")

func test_anchors() -> void:
	var dir := tmp.path_join("set_c")
	_make_set(dir)
	var an := Anchors.new()
	an.load(dir)
	var a := an.add("wisp", "idle_S", 1, 8, 6, -1)
	ok(a["id"] == 1 and an.list.size() == 1, "an anchor added")
	ok(an.on_frame("idle_E").size() == 1 and an.on_frame("walk_S").size() == 0, "it shows on every direction of its clip and no other clip")
	var doc := Doc.new()
	doc.open_set(dir, "idle", "S")
	ok(an.place(a, doc, doc.frame("idle_S", 2)) == Vector2i(8, 6), "no part masks: the same place in every frame")
	ok(an.save() and FileAccess.file_exists(dir.path_join("anchors.json")), "saved in the frame data")
	var an2 := Anchors.new()
	an2.load(dir)
	ok(an2.list.size() == 1 and an2.next_id == 2, "loads back")
	var b := an.bake(dir.path_join("export"), "test")
	ok(b["ok"] and FileAccess.file_exists(dir.path_join("export/test.anchors.json")), "bake writes the list")
	ok(an.remove(1) and an.list.is_empty(), "removed")

## the editor screen's command line, without a window: a stub app with what exec needs
func test_exec() -> void:
	var dir := tmp.path_join("set_d")
	_make_set(dir)
	var Ed = load("res://scripts/screens/editor.gd")
	var ed = Ed.new()
	ed.headless = true
	ed.open_frames(dir, "idle", "S")
	ok(ed.doc.count() == 3, "exec: the set is open")
	var r = ed.exec_line("tool pencil")
	ok(r["ok"] and ed.tool == "pencil", "tool pencil")
	r = ed.exec_line("colour #406080")
	ok(r["ok"] and Pal.same_rgb(ed.colour, Color("#406080")), "colour set")
	r = ed.exec_line("stroke 5 5 7 5")
	ok(r["ok"] and ed.doc.composite().get_pixel(6, 5).to_html(false) == "406080", "a stroke paints")
	r = ed.exec_line("colour #123456")
	ok(r["ok"] and r.get("snapped", false), "a colour off the palette is snapped while locked: %s" % r)
	ed.exec_line("lock open")
	r = ed.exec_line("colour #123456")
	ok(r["ok"] and not r.get("snapped", true) and ed.doc.palette.added == 1, "open lets it in: %s" % r)
	ed.exec_line("lock locked")
	r = ed.exec_line("select rect 0 0 4 4")
	ok(r["ok"] and Px.mask_count(ed.doc.selection) == 16, "a rectangle selection")
	r = ed.exec_line("select wand 6 6")
	ok(r["ok"] and Px.mask_count(ed.doc.selection) == 64, "wand replaces: the figure's 8x8 (%d)" % Px.mask_count(ed.doc.selection))
	r = ed.exec_line("select rect 0 0 2 2 add")
	ok(r["ok"] and Px.mask_count(ed.doc.selection) == 68, "shift adds")
	r = ed.exec_line("select none")
	ok(r["ok"] and ed.doc.selection.is_empty(), "deselect")
	r = ed.exec_line("tool fill")
	r = ed.exec_line("fill 0 0")
	ok(r["ok"] and int(r.get("count", 0)) > 100, "fill the background: %s" % r.get("count"))
	r = ed.exec_line("undo")
	ok(r["ok"] and ed.doc.composite().get_pixel(0, 0).a == 0.0, "undo the fill")
	r = ed.exec_line("redo")
	ok(r["ok"] and ed.doc.composite().get_pixel(0, 0).a == 1.0, "redo the fill")
	r = ed.exec_line("history 1")
	ok(r["ok"] and ed.history.cursor == 1, "history 1 jumps back")
	r = ed.exec_line("frame 2")
	ok(r["ok"] and ed.doc.index == 1, "frame 2 (1-based) is index 1")
	r = ed.exec_line("direction E")
	ok(r["ok"] and ed.doc.key == "idle_E", "direction E")
	r = ed.exec_line("clone_source 5 5 frame 1 direction S")
	ok(r["ok"] and ed.clone_src["key"] == "idle_S", "clone source on another direction: %s" % r)
	ed.exec_line("tool clone")
	r = ed.exec_line("stroke 9 9 9 9")
	ok(r["ok"], "a clone dab: %s" % r)
	ok(Pal.same_rgb(ed.doc.composite().get_pixel(9, 9), Color("#406080")), "the clone brought the S colour (%s)" % ed.doc.composite().get_pixel(9, 9).to_html(false))
	r = ed.exec_line("carry directions")
	ok(r["ok"] and r["landed"].size() == 2, "carry from exec: %s" % r.get("landed", []).size())
	r = ed.exec_line("layer add shade")
	ok(r["ok"] and ed.doc.current().layers.size() == 3 and ed.doc.active_layer == 2, "a layer added and active")
	r = ed.exec_line("layer merge")
	ok(r["ok"] and ed.doc.current().layers.size() == 2, "merged down")
	r = ed.exec_line("anchor add wisp 8 8")
	ok(r["ok"] and ed.anchors.list.size() == 1, "an anchor by command")
	r = ed.exec_line("anchor move 1 9 9")
	ok(r["ok"] and int(ed.anchors.by_id(1)["x"]) == 9, "moved")
	r = ed.exec_line("undo")
	ok(r["ok"] and int(ed.anchors.by_id(1)["x"]) == 8, "an anchor move undoes")
	r = ed.exec_line("pixel 9 9")
	ok(r["ok"] and r.has("hex") and r.has("oklab") and r.has("slot"), "pixel reads slot, hex, OKLab: %s" % r)
	r = ed.exec_line("size 4")
	ok(r["ok"] and ed.brush_size == 4, "brush size")
	r = ed.exec_line("mirror")
	ok(r["ok"], "mirror runs")
	r = ed.exec_line("save")
	ok(r["ok"], "save: %s" % r)
	r = ed.exec_line("info")
	ok(r["ok"] and r.has("palette"), "info")
	r = ed.exec_line("nonsense 1 2")
	ok(not r["ok"], "an unknown command says so")
	ed.free()
